
package com.acme.training.webservices;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "MenuWebService", targetNamespace = "http://webservices.training.acme.com/", wsdlLocation = "http://10.0.13.240:8080/menu?wsdl")
public class MenuWebService
    extends Service
{

    private final static URL MENUWEBSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.acme.training.webservices.MenuWebService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.acme.training.webservices.MenuWebService.class.getResource(".");
            url = new URL(baseUrl, "http://10.0.13.240:8080/menu?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://10.0.13.240:8080/menu?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        MENUWEBSERVICE_WSDL_LOCATION = url;
    }

    public MenuWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MenuWebService() {
        super(MENUWEBSERVICE_WSDL_LOCATION, new QName("http://webservices.training.acme.com/", "MenuWebService"));
    }

    /**
     * 
     * @return
     *     returns MenuWeb
     */
    @WebEndpoint(name = "MenuWebPort")
    public MenuWeb getMenuWebPort() {
        return super.getPort(new QName("http://webservices.training.acme.com/", "MenuWebPort"), MenuWeb.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MenuWeb
     */
    @WebEndpoint(name = "MenuWebPort")
    public MenuWeb getMenuWebPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices.training.acme.com/", "MenuWebPort"), MenuWeb.class, features);
    }

}
