
package com.acme.training.webservices;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "MenuWeb", targetNamespace = "http://webservices.training.acme.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MenuWeb {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "init", targetNamespace = "http://webservices.training.acme.com/", className = "com.acme.training.webservices.Init")
    @ResponseWrapper(localName = "initResponse", targetNamespace = "http://webservices.training.acme.com/", className = "com.acme.training.webservices.InitResponse")
    public void init();

    /**
     * 
     * @return
     *     returns java.util.List<com.acme.training.webservices.FoodView>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFoods", targetNamespace = "http://webservices.training.acme.com/", className = "com.acme.training.webservices.GetFoods")
    @ResponseWrapper(localName = "getFoodsResponse", targetNamespace = "http://webservices.training.acme.com/", className = "com.acme.training.webservices.GetFoodsResponse")
    public List<FoodView> getFoods();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setCustomer", targetNamespace = "http://webservices.training.acme.com/", className = "com.acme.training.webservices.SetCustomer")
    @ResponseWrapper(localName = "setCustomerResponse", targetNamespace = "http://webservices.training.acme.com/", className = "com.acme.training.webservices.SetCustomerResponse")
    public int setCustomer(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setDeliveryAddress", targetNamespace = "http://webservices.training.acme.com/", className = "com.acme.training.webservices.SetDeliveryAddress")
    @ResponseWrapper(localName = "setDeliveryAddressResponse", targetNamespace = "http://webservices.training.acme.com/", className = "com.acme.training.webservices.SetDeliveryAddressResponse")
    public int setDeliveryAddress(
        @WebParam(name = "arg0", targetNamespace = "")
        Address arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setBillingAddress", targetNamespace = "http://webservices.training.acme.com/", className = "com.acme.training.webservices.SetBillingAddress")
    @ResponseWrapper(localName = "setBillingAddressResponse", targetNamespace = "http://webservices.training.acme.com/", className = "com.acme.training.webservices.SetBillingAddressResponse")
    public int setBillingAddress(
        @WebParam(name = "arg0", targetNamespace = "")
        Address arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addFood", targetNamespace = "http://webservices.training.acme.com/", className = "com.acme.training.webservices.AddFood")
    @ResponseWrapper(localName = "addFoodResponse", targetNamespace = "http://webservices.training.acme.com/", className = "com.acme.training.webservices.AddFoodResponse")
    public int addFood(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "sendOrder", targetNamespace = "http://webservices.training.acme.com/", className = "com.acme.training.webservices.SendOrder")
    @ResponseWrapper(localName = "sendOrderResponse", targetNamespace = "http://webservices.training.acme.com/", className = "com.acme.training.webservices.SendOrderResponse")
    public void sendOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "viewOrder", targetNamespace = "http://webservices.training.acme.com/", className = "com.acme.training.webservices.ViewOrder")
    @ResponseWrapper(localName = "viewOrderResponse", targetNamespace = "http://webservices.training.acme.com/", className = "com.acme.training.webservices.ViewOrderResponse")
    public String viewOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
